source "https://rubygems.org"
ruby "2.1.2"
gem 'sinatra'
gem 'twilio-ruby'
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem "data_mapper"
gem "dm-postgres-adapter"
gem "pg"
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
